import os
import re
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Annotated, AsyncIterator, Generic, TypeVar

from fastapi import Depends

from pydantic import BaseModel

from core.settings import Settings, get_settings


T = TypeVar("T", bound=BaseModel)


@dataclass
class LLMResponse:
    text: str
    model: str
    input_tokens: int
    output_tokens: int
    latency_ms: float
    raw: object
    sources: list[str] | None = None


@dataclass
class ParsedResponse(Generic[T]):
    parsed: T | None
    text: str
    model: str
    input_tokens: int
    output_tokens: int
    latency_ms: float
    raw: object
    sources: list[str]


class LLMClient(ABC):
    async def aclose(self) -> None:
        """Release any underlying HTTP connections. No-op by default."""
        return None

    @abstractmethod
    async def _call(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float,
        max_tokens: int,
        model: str | None = None,
        web_search: bool = False,
    ) -> LLMResponse:
        ...

    @abstractmethod
    async def _parse(
        self,
        system_prompt: str,
        user_prompt: str,
        response_format: type[T],
        temperature: float,
        max_tokens: int,
        model: str | None = None,
        web_search: bool = False,
    ) -> ParsedResponse[T]:
        ...

    @abstractmethod
    def provider_name(self) -> str:
        ...

    async def generate(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.3,
        max_tokens: int = 1000,
        model: str | None = None,
        web_search: bool = False,
    ) -> LLMResponse:
        return await self._call(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=temperature,
            max_tokens=max_tokens,
            model=model,
            web_search=web_search,
        )

    async def parse(
        self,
        system_prompt: str,
        user_prompt: str,
        response_format: type[T],
        temperature: float = 0.3,
        max_tokens: int = 1000,
        model: str | None = None,
        web_search: bool = False,
    ) -> ParsedResponse[T]:
        return await self._parse(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            response_format=response_format,
            temperature=temperature,
            max_tokens=max_tokens,
            model=model,
            web_search=web_search,
        )


class MockLLMClient(LLMClient):
    async def _call(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float,
        max_tokens: int,
        model: str | None = None,
        web_search: bool = False,
    ) -> LLMResponse:
        return LLMResponse(
            text="Generated by mock LLM client.",
            model=model or "mock-model",
            input_tokens=0,
            output_tokens=0,
            latency_ms=0.0,
            raw={},
            sources=[],
        )

    async def _parse(
        self,
        system_prompt: str,
        user_prompt: str,
        response_format: type[T],
        temperature: float,
        max_tokens: int,
        model: str | None = None,
        web_search: bool = False,
    ) -> ParsedResponse[T]:
        return ParsedResponse(
            parsed=None,
            text="Generated by mock LLM client.",
            model=model or "mock-model",
            input_tokens=0,
            output_tokens=0,
            latency_ms=0.0,
            raw={},
            sources=[],
        )

    def provider_name(self) -> str:
        return "mock"


class AnthropicLLMClient(LLMClient):
    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._client = None

    def _get_client(self):
        if self._client is not None:
            return self._client

        api_key = self._settings.anthropic_api_key or os.getenv("ANTHROPIC_API_KEY")
        if not api_key:
            raise RuntimeError(
                "Anthropic API key is missing. Set MANAGER_AGENT_ANTHROPIC_API_KEY or ANTHROPIC_API_KEY."
            )

        from anthropic import AsyncAnthropic

        self._client = AsyncAnthropic(api_key=api_key)
        return self._client

    async def aclose(self) -> None:
        if self._client is not None:
            await self._client.close()
            self._client = None

    async def _call(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float,
        max_tokens: int,
        model: str | None = None,
        web_search: bool = False,
    ) -> LLMResponse:
        if web_search:
            raise NotImplementedError("web_search=True is currently only supported by OpenAILLMClient.")
        start = time.time()
        mdl = model or self._settings.primary_model_name()
        client = self._get_client()
        r = await client.messages.create(
            model=mdl,
            max_tokens=max_tokens,
            temperature=temperature,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
        )
        text = ""
        if r.content:
            first = r.content[0]
            text = getattr(first, "text", "") or ""
        return LLMResponse(
            text=text,
            model=mdl,
            input_tokens=r.usage.input_tokens,
            output_tokens=r.usage.output_tokens,
            latency_ms=round((time.time() - start) * 1000, 1),
            raw={"id": r.id, "stop_reason": r.stop_reason},
            sources=[],
        )

    async def _parse(
        self,
        system_prompt: str,
        user_prompt: str,
        response_format: type[T],
        temperature: float,
        max_tokens: int,
        model: str | None = None,
        web_search: bool = False,
    ) -> ParsedResponse[T]:
        if web_search:
            raise NotImplementedError("web_search=True is currently only supported by OpenAILLMClient.")
        start = time.time()
        mdl = model or self._settings.primary_model_name()
        client = self._get_client()
        tool = {
            "name": "emit_structured_output",
            "description": "Return the result as structured data matching the schema.",
            "input_schema": response_format.model_json_schema(),
        }
        r = await client.messages.create(
            model=mdl,
            max_tokens=max_tokens,
            temperature=temperature,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
            tools=[tool],
            tool_choice={"type": "tool", "name": "emit_structured_output"},
        )
        block = next((b for b in r.content if getattr(b, "type", None) == "tool_use"), None)
        parsed: T | None = None
        if block is not None:
            try:
                parsed = response_format.model_validate(block.input)
            except Exception:
                parsed = None
        text = parsed.model_dump_json() if parsed is not None else ""
        return ParsedResponse(
            parsed=parsed,
            text=text,
            model=mdl,
            input_tokens=r.usage.input_tokens,
            output_tokens=r.usage.output_tokens,
            latency_ms=round((time.time() - start) * 1000, 1),
            raw={"id": r.id, "stop_reason": r.stop_reason},
            sources=[],
        )

    def provider_name(self) -> str:
        return "anthropic"


class OpenAILLMClient(LLMClient):
    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._client = None

    def _get_client(self):
        if self._client is not None:
            return self._client

        api_key = self._settings.openai_api_key or os.getenv("OPENAI_API_KEY")
        if not api_key:
            raise RuntimeError(
                "OpenAI API key is missing. Set MANAGER_AGENT_OPENAI_API_KEY or OPENAI_API_KEY."
            )

        from openai import AsyncOpenAI

        self._client = AsyncOpenAI(api_key=api_key, timeout=self._settings.llm_timeout_seconds)
        return self._client

    async def aclose(self) -> None:
        if self._client is not None:
            await self._client.close()
            self._client = None

    async def _call(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float,
        max_tokens: int,
        model: str | None = None,
        web_search: bool = False,
    ) -> LLMResponse:
        from openai import BadRequestError

        client = self._get_client()
        start = time.time()
        mdl = model or self._settings.primary_model_name()

        if web_search:
            response = await client.responses.create(
                model=mdl,
                input=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                tools=[{"type": "web_search_preview"}],
                max_output_tokens=max_tokens,
                temperature=temperature,
            )
            output_text = (response.output_text or "").strip()
            sources: list[str] = []
            for item in getattr(response, "output", []) or []:
                content = getattr(item, "content", None) or []
                for c in content:
                    url = getattr(c, "url", None)
                    if isinstance(url, str) and url:
                        sources.append(url)
            return LLMResponse(
                text=output_text,
                model=mdl,
                input_tokens=getattr(getattr(response, "usage", None), "input_tokens", 0) or 0,
                output_tokens=getattr(getattr(response, "usage", None), "output_tokens", 0) or 0,
                latency_ms=round((time.time() - start) * 1000, 1),
                raw={"id": getattr(response, "id", None)},
                sources=sources,
            )

        newer = mdl.startswith(("gpt-5", "o1", "o3", "o4"))
        kwargs = {
            "model": mdl,
            "temperature": temperature,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
        }
        kwargs["max_completion_tokens" if newer else "max_tokens"] = max_tokens

        for _ in range(6):
            try:
                r = await client.chat.completions.create(**kwargs)
                break
            except BadRequestError as e:
                msg = str(e)
                m = re.search(r"'param': '(\w+)'", msg) or re.search(r"parameter: '(\w+)'", msg)
                bad = m.group(1) if m else None
                if bad == "max_tokens" and "max_tokens" in kwargs:
                    kwargs["max_completion_tokens"] = kwargs.pop("max_tokens")
                elif bad and bad in kwargs:
                    kwargs.pop(bad)
                else:
                    raise

        c = r.choices[0]
        text = c.message.content or ""
        return LLMResponse(
            text=text,
            model=mdl,
            input_tokens=r.usage.prompt_tokens,
            output_tokens=r.usage.completion_tokens,
            latency_ms=round((time.time() - start) * 1000, 1),
            raw={"id": r.id, "finish_reason": c.finish_reason},
            sources=[],
        )

    async def _parse(
        self,
        system_prompt: str,
        user_prompt: str,
        response_format: type[T],
        temperature: float,
        max_tokens: int,
        model: str | None = None,
        web_search: bool = False,
    ) -> ParsedResponse[T]:
        # Follows notebook style: OpenAI web search uses Responses API path.
        if web_search:
            call_response = await self._call(
                system_prompt=system_prompt,
                user_prompt=(
                    user_prompt
                    + "\n\nUse web search where needed and return ONLY valid JSON matching the requested schema."
                ),
                temperature=temperature,
                max_tokens=max_tokens,
                model=model,
                web_search=True,
            )
        else:
            call_response = await self._call(
                system_prompt=system_prompt,
                user_prompt=(
                    user_prompt
                    + "\n\nReturn ONLY valid JSON matching the requested schema."
                ),
                temperature=temperature,
                max_tokens=max_tokens,
                model=model,
                web_search=False,
            )

        parsed: T | None = None
        try:
            parsed = response_format.model_validate_json(call_response.text)
        except Exception:
            parsed = None

        return ParsedResponse(
            parsed=parsed,
            text=call_response.text,
            model=call_response.model,
            input_tokens=call_response.input_tokens,
            output_tokens=call_response.output_tokens,
            latency_ms=call_response.latency_ms,
            raw=call_response.raw,
            sources=call_response.sources or [],
        )

    def provider_name(self) -> str:
        return "openai"


def create_llm_client(settings: Settings) -> LLMClient:
    if settings.llm_provider == "openai":
        return OpenAILLMClient(settings)
    if settings.llm_provider == "anthropic":
        return AnthropicLLMClient(settings)
    return MockLLMClient()


async def get_llm_client(
    settings: Annotated[Settings, Depends(get_settings)],
) -> AsyncIterator[LLMClient]:
    client = create_llm_client(settings)
    try:
        yield client
    finally:
        await client.aclose()
